version: '3.8'

services:
  jairouter-dev:
    image: sodlinken/jairouter:dev
    container_name: jairouter-dev
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./src:/app/src:ro
    networks:
      - jairouter-network

networks:
  jairouter-network:
    driver: bridge