site_name: JAiRouter 文档
site_description: AI模型服务路由和负载均衡网关
site_author: Lincoln
site_url: https://lincoln-cn.github.io/JAiRouter

repo_name: Lincoln-cn/jairouter
repo_url: https://github.com/Lincoln-cn/jairouter
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - content.tabs.link
    - navigation.tracking

plugins:
  - search:
      lang: 
        - zh
        - en
      separator: '[\s\-\.]+'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
        remove_empty_space: true
        remove_redundant_attributes: true
        remove_script_type_attributes: true
        remove_style_link_type_attributes: true
        minify_css: true
        minify_js: true
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: zh
          default: true
          name: 中文
          build: true
          site_name: "JAiRouter 文档"
        - locale: en
          name: English
          build: true
          site_name: "JAiRouter Documentation"
          nav_translations:
            首页: Home
            入门: Getting Started
            安装指南: Installation Guide
            快速开始: Quick Start
            第一步: First Steps
            配置指南: Configuration
            应用配置: Application Config
            动态配置: Dynamic Config
            负载均衡: Load Balancing
            限流配置: Rate Limiting
            熔断器: Circuit Breaker
            API参考: API Reference
            统一API: Universal API
            管理API: Management API
            监控API: Monitoring API
            OpenAPI规范: OpenAPI Specification
            部署指南: Deployment
            Docker部署: Docker Deployment
            Kubernetes部署: Kubernetes Deployment
            生产环境: Production
            中国优化: China Optimization
            GitHub Pages: GitHub Pages
            监控指南: Monitoring
            监控设置: Setup
            仪表板: Dashboards
            告警配置: Alerts
            故障排查: Troubleshooting
            开发指南: Development
            架构说明: Architecture
            贡献指南: Contributing
            测试指南: Testing
            代码质量: Code Quality
            部署测试: Deployment Testing
            性能优化: Performance Optimization
            常见问题: Common Issues
            性能问题: Performance Issues
            调试指南: Debugging Guide
            参考资料: Reference
            更新日志: Changelog
            发展路线图: Roadmap
            FAQ: FAQ
            术语表: Glossary
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      fallback_to_build_date: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - 首页: zh/index.md
  - 入门:
    - zh/getting-started/index.md
    - 安装指南: zh/getting-started/installation.md
    - 快速开始: zh/getting-started/quick-start.md
    - 第一步: zh/getting-started/first-steps.md
  - 配置指南:
    - zh/configuration/index.md
    - 应用配置: zh/configuration/application-config.md
    - 动态配置: zh/configuration/dynamic-config.md
    - 负载均衡: zh/configuration/load-balancing.md
    - 限流配置: zh/configuration/rate-limiting.md
    - 熔断器: zh/configuration/circuit-breaker.md
  - API参考:
    - zh/api-reference/index.md
    - 统一API: zh/api-reference/universal-api.md
    - 管理API: zh/api-reference/management-api.md
    - OpenAPI规范: zh/api-reference/openapi-spec.md
  - 部署指南:
    - zh/deployment/index.md
    - Docker部署: zh/deployment/docker.md
    - Kubernetes部署: zh/deployment/kubernetes.md
    - 生产环境: zh/deployment/production.md
    - 中国优化: zh/deployment/china-optimization.md
    - GitHub Pages: zh/deployment/github-pages.md
  - 监控指南:
    - zh/monitoring/index.md
    - 监控设置: zh/monitoring/setup.md
    - 仪表板: zh/monitoring/dashboards.md
    - 告警配置: zh/monitoring/alerts.md
    - 故障排查: zh/monitoring/troubleshooting.md
  - 开发指南:
    - zh/development/index.md
    - 架构说明: zh/development/architecture.md
    - 贡献指南: zh/development/contributing.md
    - 测试指南: zh/development/testing.md
    - 代码质量: zh/development/code-quality.md
    - 部署测试: zh/development/deployment-testing.md
    - 性能优化: zh/development/performance-optimization.md
  - 故障排查:
    - zh/troubleshooting/index.md
    - 常见问题: zh/troubleshooting/common-issues.md
    - 性能问题: zh/troubleshooting/performance.md
    - 调试指南: zh/troubleshooting/debugging.md
  - 参考资料:
    - zh/reference/index.md
    - 更新日志: zh/reference/changelog.md
    - 发展路线图: zh/reference/roadmap.md
    - FAQ: zh/reference/faq.md
    - 术语表: zh/reference/glossary.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lincoln-cn/jairouter
      name: GitHub Repository
    - icon: fontawesome/solid/book
      link: https://lincoln-cn.github.io/JAiRouter
      name: Documentation
  version:
    provider: mike
    default: latest
  alternate:
    - name: 中文
      link: /
      lang: zh
    - name: English
      link: /en/
      lang: en
  analytics:
    provider: google
    property: G-C3YPY477RC  # 替换为实际的 Google Analytics ID
    feedback:
      title: 这个页面有帮助吗？
      ratings:
        - icon: material/emoticon-happy-outline
          name: 有帮助
          data: 1
          note: >-
            感谢您的反馈！
        - icon: material/emoticon-sad-outline
          name: 需要改进
          data: 0
          note: >-
            感谢您的反馈！请通过 GitHub Issues 告诉我们如何改进。

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/language-switcher.js

copyright: Copyright &copy; 2025 JAiRouter Team
