-- ========================================
-- V1 基线：当前实体模型的完整 schema（PostgreSQL 路径，issue #191）
-- ========================================
-- 来源：Hibernate 的 schema 导出，不是手写 DDL。生成方式（对空库执行，本设置只写脚本不落库）：
--   java -jar model-router.jar \
--     --spring.datasource.url=jdbc:postgresql://<host>:<port>/<db> \
--     --spring.jpa.hibernate.ddl-auto=create \
--     --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create \
--     --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=<file>
-- 因为直接由实体元数据生成，它与实体映射天然一致 —— 这是 ddl-auto: validate 能通过的前提。
--
-- 语义：
--   * 空库：Flyway 从头执行本文件，建成与实体一致的 schema（版本记为 1）。
--   * 已有库：spring.flyway.baseline-on-migrate=true 使其被记为基线 1 而不执行本文件。
--     注意基线不会修补旧库缺失的列或类型 —— 见 docs/*/deployment/database.md 的升级前置说明。
--
-- 维护约定：
--   * 已发布的迁移脚本不可再改（Flyway 按校验和判定），schema 变更请新增 V2__/V3__… 增量脚本。
--   * 本目录只覆盖 PostgreSQL；H2 有一套等价但类型不同的基线，见 ../h2/V1__baseline.sql。
-- ========================================

    create table api_call_history (
        circuit_broken boolean not null,
        http_status_code integer,
        is_success boolean not null,
        rate_limited boolean not null,
        request_hour integer not null,
        completion_tokens bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        prompt_tokens bigint not null,
        response_time_ms bigint,
        total_tokens bigint not null,
        request_date varchar(10) not null,
        request_method varchar(10) not null,
        record_level varchar(20),
        client_ip varchar(50),
        service_type varchar(50) not null,
        content_type varchar(100),
        error_code varchar(100),
        provider varchar(100),
        request_id varchar(100) not null,
        trace_id varchar(100) not null,
        instance_url varchar(500),
        request_path varchar(500) not null,
        response_body_summary varchar(500),
        user_agent varchar(500),
        error_message varchar(1000),
        request_body_summary varchar(1000),
        api_key_id varchar(255),
        instance_name varchar(255),
        model_name varchar(255) not null,
        request_body_encrypted TEXT,
        response_body_encrypted TEXT,
        user_id varchar(255),
        primary key (id)
    );

    create table circuit_breaker_global_config (
        adaptive_threshold_enabled boolean,
        cleanup_interval_minutes integer,
        default_failure_threshold integer,
        default_success_threshold integer,
        history_retention_days integer,
        state_sync_interval_minutes integer,
        default_timeout_ms bigint,
        id bigint not null,
        updated_at timestamp(6),
        primary key (id)
    );

    create table circuit_breaker_metrics (
        adjusted_failure_threshold integer,
        adjustment_applied boolean,
        current_failure_threshold integer,
        failure_rate float(53),
        avg_response_time_ms bigint,
        failure_calls bigint not null,
        id bigint generated by default as identity,
        success_calls bigint not null,
        total_calls bigint not null,
        updated_at timestamp(6),
        window_end timestamp(6),
        window_start timestamp(6),
        service_type varchar(32),
        instance_id varchar(64) not null,
        adjustment_reason varchar(512),
        instance_name varchar(255),
        primary key (id)
    );

    create table circuit_breaker_state_history (
        failure_count integer,
        success_count integer,
        changed_at timestamp(6) not null,
        id bigint generated by default as identity,
        current_state varchar(16) not null check (current_state in ('CLOSED','OPEN','HALF_OPEN')),
        previous_state varchar(16) not null check (previous_state in ('CLOSED','OPEN','HALF_OPEN')),
        service_type varchar(32),
        trigger_reason varchar(32),
        instance_id varchar(64) not null,
        instance_name varchar(255),
        primary key (id)
    );

    create table config_audit_log (
        id bigint generated by default as identity,
        timestamp timestamp(6) with time zone not null,
        change_type varchar(50) not null,
        entity_type varchar(50),
        entity_id varchar(100),
        service_type varchar(100),
        user_id varchar(100),
        description varchar(500),
        new_config TEXT,
        old_config TEXT,
        primary key (id)
    );

    create table config_change_audit_log (
        id bigint generated by default as identity,
        timestamp timestamp(6),
        change_summary varchar(255),
        config_key varchar(255),
        config_type varchar(255),
        event_id varchar(255),
        new_value varchar(255),
        old_value varchar(255),
        operation varchar(255),
        operator varchar(255),
        operator_ip varchar(255),
        reason varchar(255),
        trace_id varchar(255),
        primary key (id)
    );

    create table config_data (
        is_latest boolean not null,
        version integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        config_key varchar(255) not null,
        config_value TEXT not null,
        primary key (id)
    );

    create table config_version_history (
        id bigint generated by default as identity,
        timestamp timestamp(6) with time zone not null,
        status varchar(20),
        version_number varchar(50) not null,
        service_type varchar(100),
        user_id varchar(100),
        description varchar(500),
        config_snapshot TEXT,
        primary key (id)
    );

    create table exception_events (
        is_aggregated boolean not null,
        line_number integer,
        created_at timestamp(6),
        first_occurrence timestamp(6) not null,
        id bigint generated by default as identity,
        last_occurrence timestamp(6) not null,
        occurred_at timestamp(6) not null,
        occurrence_count bigint not null,
        response_time_ms bigint,
        http_status varchar(10),
        client_ip varchar(50),
        error_category varchar(50),
        service_type varchar(50),
        error_code varchar(100),
        provider varchar(100),
        service_name varchar(100),
        span_id varchar(100),
        trace_id varchar(100),
        class_name varchar(500),
        exception_type varchar(500) not null,
        user_agent varchar(500),
        exception_message varchar(1000),
        sanitized_message varchar(1000),
        event_id varchar(255) not null unique,
        instance_name varchar(255),
        metadata TEXT,
        method_name varchar(255),
        model_name varchar(255),
        operation varchar(255) not null,
        request_id varchar(255),
        sanitized_stack_trace TEXT,
        primary key (id)
    );

    create table exception_stats_hourly (
        created_at timestamp(6),
        failure_count bigint not null,
        hour_timestamp timestamp(6) not null,
        id bigint generated by default as identity,
        success_count bigint not null,
        total_count bigint not null,
        unique_client_ips bigint not null,
        unique_trace_ids bigint not null,
        updated_at timestamp(6),
        error_category varchar(50),
        error_code varchar(100),
        service_name varchar(100),
        exception_type varchar(500) not null,
        operation varchar(255),
        primary key (id),
        constraint uk_exception_stats_hour unique (hour_timestamp, exception_type, error_code, operation)
    );

    create table instance_circuit_breaker (
        enabled boolean not null,
        failure_threshold integer,
        success_threshold integer,
        timeout_ms integer,
        created_at timestamp(6),
        id bigint generated by default as identity,
        instance_id bigint not null unique,
        updated_at timestamp(6),
        primary key (id)
    );

    create table instance_rate_limit (
        capacity integer,
        client_ip_enable boolean,
        enabled boolean not null,
        rate integer,
        created_at timestamp(6),
        id bigint generated by default as identity,
        instance_id bigint not null unique,
        updated_at timestamp(6),
        algorithm varchar(255),
        rate_limit_key varchar(255),
        scope varchar(255),
        primary key (id)
    );

    create table jwt_accounts (
        enabled boolean,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        password varchar(255) not null,
        roles varchar(255),
        username varchar(255) not null unique,
        primary key (id)
    );

    create table quota_ledger (
        id bigint generated by default as identity,
        request_count bigint not null,
        token_count bigint not null,
        updated_at timestamp(6) not null,
        window_start timestamp(6) not null,
        window_type varchar(20) not null,
        service_type varchar(50) not null,
        tenant_id varchar(64) not null,
        api_key_id varchar(128) not null,
        user_id varchar(128) not null,
        model varchar(255) not null,
        primary key (id),
        constraint uk_quota_ledger_dimension_window unique (tenant_id, api_key_id, user_id, service_type, model, window_type, window_start)
    );

    create table role_permissions (
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        role_name varchar(64) not null,
        permission_code varchar(128) not null,
        primary key (id),
        constraint uk_role_permission unique (role_name, permission_code)
    );

    create table security_audit (
        success boolean not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        timestamp timestamp(6) not null,
        risk_level varchar(20) check (risk_level in ('LOW','MEDIUM','HIGH','CRITICAL')),
        client_ip varchar(50),
        event_category varchar(50),
        action varchar(100),
        event_type varchar(100) not null check (event_type in ('JWT_TOKEN_ISSUED','JWT_TOKEN_REFRESHED','JWT_TOKEN_REVOKED','JWT_TOKEN_VALIDATED','JWT_TOKEN_EXPIRED','API_KEY_CREATED','API_KEY_USED','API_KEY_REVOKED','API_KEY_EXPIRED','API_KEY_UPDATED','SECURITY_ALERT','SUSPICIOUS_ACTIVITY','AUTHENTICATION_FAILED','AUTHORIZATION_FAILED','SYSTEM_CLEANUP','SYSTEM_MAINTENANCE')),
        geo_location varchar(100),
        device_info varchar(500),
        resource varchar(500),
        user_agent varchar(500),
        details varchar(1000),
        failure_reason varchar(1000),
        event_id varchar(255) not null unique,
        metadata TEXT,
        request_id varchar(255),
        resource_id varchar(255),
        session_id varchar(255),
        user_id varchar(255),
        primary key (id)
    );

    create table security_blacklist (
        added_at timestamp(6) not null,
        created_at timestamp(6),
        expires_at TIMESTAMP NULL,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        blacklist_type varchar(20) not null check (blacklist_type in ('TOKEN','IP','DEVICE')),
        risk_level varchar(20) check (risk_level in ('LOW','MEDIUM','HIGH','CRITICAL')),
        status varchar(20) not null check (status in ('ACTIVE','EXPIRED','REMOVED')),
        source varchar(50) check (source in ('MANUAL','AUTO','SYSTEM')),
        reason varchar(1000),
        metadata varchar(2000),
        added_by varchar(255),
        target_hash varchar(255),
        target_value varchar(255) not null,
        user_id varchar(255),
        primary key (id),
        unique (blacklist_type, target_value)
    );

    create table service_config (
        is_latest boolean,
        version integer,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        adapter varchar(255),
        config_key varchar(255) not null,
        load_balance_type varchar(255),
        service_type varchar(255) not null,
        primary key (id)
    );

    create table service_instance (
        weight integer,
        created_at timestamp(6),
        id bigint generated by default as identity,
        service_config_id bigint not null,
        updated_at timestamp(6),
        adapter varchar(255),
        base_url varchar(255) not null,
        error_message varchar(255),
        health_status varchar(255),
        instance_id varchar(255),
        instance_name varchar(255) not null,
        path varchar(255),
        status varchar(255),
        headers jsonb,
        tags jsonb,
        primary key (id)
    );

    create table token_usage (
        day_of_week integer,
        hour_num integer,
        is_success boolean,
        month_num integer,
        week_of_year integer,
        year_num integer,
        completion_tokens bigint,
        created_at timestamp(6),
        id bigint generated by default as identity,
        occurred_at timestamp(6) not null,
        prompt_tokens bigint,
        response_time_ms bigint,
        total_tokens bigint not null,
        usage_date varchar(10),
        client_ip varchar(50),
        service_type varchar(50) not null,
        error_code varchar(100),
        provider varchar(100),
        trace_id varchar(100),
        instance_url varchar(500),
        error_message varchar(1000),
        api_key_id varchar(255),
        instance_name varchar(255),
        metadata TEXT,
        model_name varchar(255) not null,
        user_id varchar(255),
        primary key (id)
    );

    create index idx_call_history_trace_id 
       on api_call_history (trace_id);

    create index idx_call_history_created_at 
       on api_call_history (created_at);

    create index idx_call_history_model 
       on api_call_history (model_name);

    create index idx_call_history_api_key 
       on api_call_history (api_key_id);

    create index idx_call_history_service_type 
       on api_call_history (service_type);

    create index idx_call_history_status 
       on api_call_history (http_status_code);

    create index idx_call_history_date 
       on api_call_history (request_date, request_hour);

    create index idx_cb_metrics_instance_id 
       on circuit_breaker_metrics (instance_id);

    create index idx_window_end 
       on circuit_breaker_metrics (window_end);

    create index idx_instance_id 
       on circuit_breaker_state_history (instance_id);

    create index idx_changed_at 
       on circuit_breaker_state_history (changed_at);

    create index idx_instance_changed 
       on circuit_breaker_state_history (instance_id, changed_at);

    create index idx_audit_service_type 
       on config_audit_log (service_type);

    create index idx_config_audit_user_id 
       on config_audit_log (user_id);

    create index idx_config_audit_timestamp 
       on config_audit_log (timestamp);

    create index idx_version_service_type 
       on config_version_history (service_type);

    create index idx_version_number 
       on config_version_history (version_number);

    create index idx_version_timestamp 
       on config_version_history (timestamp);

    create index idx_exception_event_id 
       on exception_events (event_id);

    create index idx_exception_type 
       on exception_events (exception_type);

    create index idx_exception_occurred_at 
       on exception_events (occurred_at);

    create index idx_exception_operation 
       on exception_events (operation);

    create index idx_exception_error_code 
       on exception_events (error_code);

    create index idx_exception_error_category 
       on exception_events (error_category);

    create index idx_exception_trace_id 
       on exception_events (trace_id);

    create index idx_exception_aggregated 
       on exception_events (is_aggregated);

    create index idx_exception_last_occurrence 
       on exception_events (last_occurrence);

    create index idx_exception_stats_hour_ts 
       on exception_stats_hourly (hour_timestamp);

    create index idx_exception_stats_hour_type 
       on exception_stats_hourly (exception_type);

    create index idx_exception_stats_hour_category 
       on exception_stats_hourly (error_category);

    create index idx_exception_stats_hour_operation 
       on exception_stats_hourly (operation);

    create index idx_quota_ledger_api_key 
       on quota_ledger (api_key_id);

    create index idx_quota_ledger_window 
       on quota_ledger (window_type, window_start);

    create index idx_audit_timestamp 
       on security_audit (timestamp);

    create index idx_audit_user_id 
       on security_audit (user_id);

    create index idx_audit_event_type 
       on security_audit (event_type);

    create index idx_audit_client_ip 
       on security_audit (client_ip);

    create index idx_audit_category 
       on security_audit (event_category);

    create index idx_audit_resource_id 
       on security_audit (resource_id);

    create index idx_audit_risk_level 
       on security_audit (risk_level);

    create index idx_token_usage_model 
       on token_usage (model_name);

    create index idx_token_usage_service_type 
       on token_usage (service_type);

    create index idx_token_usage_occurred_at 
       on token_usage (occurred_at);

    create index idx_token_usage_api_key 
       on token_usage (api_key_id);

    create index idx_token_usage_trace_id 
       on token_usage (trace_id);
