# 测试环境配置
spring:
  profiles:
    active: test

# 日志配置
logging:
  level:
    org.unreal.modelrouter.controller: INFO
    org.unreal.modelrouter.config: INFO
    org.unreal.modelrouter.checker: INFO
    org.unreal.modelrouter.store: INFO
    org.unreal.modelrouter.loadbalancer: WARN
    org.unreal.modelrouter.ratelimit: WARN
    org.unreal.modelrouter.circuitbreaker: WARN
    org.springframework: WARN
    org.apache.http: WARN
    io.netty: WARN
    reactor.netty: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-}] %logger{50} - %msg%n"

# 测试环境特定配置
server:
  port: 8080

# 测试环境存储配置
store:
  type: file
  path: "config-test/"

# WebClient 测试环境配置
webclient:
  connection-timeout: 8s
  read-timeout: 20s
  write-timeout: 20s
  max-in-memory-size: 8MB